Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    
    # メモリの設定
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "10240"
    end
  
    # ポートの転送設定
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    # config.vm.network "forwarded_port", guest: 5432, host: 5432
  end
  